customer_sales/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.customers_list, name='customers_list'),
    path('customer/<int:pk>/', views.customer_detail, name='customer_detail'),
    path('customer/<int:pk>/edit/', views.customer_edit, name='customer_edit'),
    path('customer/<int:pk>/delete/', views.customer_delete, name='customer_delete'),
    path('customer/<int:customer_id>/sale/add/', views.sale_add, name='sale_add'),
    path('add_customer/', views.add_customer, name='add_customer'),
    path('warehouses/', views.warehouse_list, name='warehouse_list'),
    path('add_warehouse', views.add_warehouse, name='warehouse_add'),
    path('warehouse/<int:pk>/edit/', views.warehouse_edit, name='warehouse_edit'),
    path('warehouse/<int:pk>/', views.warehouse_detail, name='warehouse_detail'),
    path('warehouse/<int:pk>/delete/', views.warehouse_delete, name='warehouse_delete'),
    path('items/', views.item_list, name='item_list'),
    path('add_item', views.add_item, name='item_add'),
    path('sales/', views.sales_list, name='sales_list'),
    path('sales/add/', views.sale_add, name='sales_add'),
    path('item/<int:pk>/edit/', views.item_edit, name='item_edit'),
    path('item/<int:pk>/', views.item_detail, name='item_detail'),
    path('item/<int:pk>/delete/', views.item_delete, name='item_delete'),
    path('item/<int:item_id>/move/', views.move_inventory_item, name='move_inventory_item'),
    path('items/bulk-move/', views.bulk_move_items, name='bulk_move_items'),
    path('sales/<int:pk>/', views.sale_detail, name='sale_detail'),
    path('sales/<int:pk>/edit/', views.sale_edit, name='sale_edit'),
    path('sales/<int:pk>/delete/', views.sale_delete, name='sale_delete'),
    path('paygo_sales/', views.paygo_sales, name='paygo_sales'),
    path('paygo_sales/detail/<str:id>/', views.sale_detail_paygo, name='paygo_sale_detail'),
    path('paygo_sales_non_metered/', views.paygo_sales_non_metered, name='paygo_sales_non_metered'),
    path('export/customers/', views.export_customer_data, name='export_customers'),
    path('export/sales/', views.export_sales_data, name='export_sales'),
    path('export/paygoScode/', views.export_paygo_data, name='export_paygoscode'),
    path('export/paygoScodeNonmetered/', views.export_paygoNonmetered_data, name='export_paygoscodenonmetered'),
    path('export/warehouse/<int:pk>/items/', views.export_warehouse_items, name='export_warehouse_items'),
    path('export/items/', views.export_items, name='export_items'),
]


customer_sales/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now


class userProfile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    tnc_flag = models.BooleanField(default=False)
    org_name = models.CharField(max_length=50)
    org_address = models.CharField(null=True, blank=True, max_length=500)
    org_phone_number = models.CharField(max_length=15, null=True, blank=True)
    org_email = models.EmailField(blank=True, null=True)

    def __str__(self):
        return str(self.user)
    class Meta:
        db_table = 'customer_sales_userProfile'

####################################FOR INVENTORY SYSTEM#######################

class Warehouse(models.Model):
    name = models.CharField(max_length=100, unique=True)
    location = models.CharField(max_length=255)

    def __str__(self):
        return self.name
    class Meta:
        db_table = 'warehouses'
    
class InventoryItem(models.Model):
    name = models.CharField(max_length=100)
    serial_number = models.CharField(max_length=100, unique=True)
    product_type = models.CharField(max_length=100)
    date_added = models.DateField(auto_now_add=True)
    current_warehouse = models.ForeignKey(Warehouse, on_delete=models.PROTECT, related_name='inventory_items')

    def __str__(self):
        return f"{self.name} ({self.serial_number})"
    class Meta:
        db_table = 'inventory_items'
    @property
    def days_in_current_warehouse(self):
        # Get the most recent movement *into* the current warehouse
        last_movement_to_current = self.movements.filter(to_warehouse=self.current_warehouse).order_by('-date_moved').first()
        
        if last_movement_to_current:
            return (now() - last_movement_to_current.date_moved).days
        return (now() - self.date_added).days  # Fallback for items never moved
    
class InventoryMovement(models.Model):
    item = models.ForeignKey(InventoryItem, on_delete=models.CASCADE, related_name='movements')
    from_warehouse = models.ForeignKey(Warehouse, on_delete=models.SET_NULL, null=True,blank=True, related_name='moved_from')
    to_warehouse = models.ForeignKey(Warehouse, on_delete=models.SET_NULL, null=True, related_name='moved_to')
    moved_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    date_moved = models.DateTimeField(auto_now_add=True)
    note = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"{self.item.serial_number} → {self.to_warehouse.name} by {self.moved_by} on {self.date_moved}"
    class Meta:
        db_table = 'inventory_movements'
        ordering = ['-date_moved']


########################POWERPAY INTERNAL MODELS###################
class InternalCustomer(models.Model):
    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female'),
        ('P', 'Prefer not to say'),
        ('O', 'Other'),
    ]
    
    #HOUSEHOLD_CHOICES = [
        #('M', 'Male headed'),
        #('F', 'Female headed'),
        #('C', 'Child headed'),
        #('O', 'Other'),
        #('P', 'Prefer not to say'),
    #]
    
    #LANGUAGE_CHOICES = [
        #('EN', 'English'),
        #('SW', 'Kiswahili'),
        #('NA', 'Native'),
    #]

    name = models.CharField(max_length=255)
    external_id = models.CharField(max_length=100)
    id_number = models.CharField(max_length=20, unique=True)
    phone_number = models.CharField(max_length=15)
    #alternate_phone_number = models.CharField(max_length=15, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    #country = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    #household_type = models.CharField(max_length=1, choices=HOUSEHOLD_CHOICES)
    household_size = models.IntegerField()
    #preferred_language = models.CharField(max_length=2, choices=LANGUAGE_CHOICES)
    date = models.DateTimeField(auto_now_add=True)
    county = models.CharField(max_length=100, null=True, blank=True)
    sub_county = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'customer_sales_customer_internal'  # Default table for regular users


class InternalSale(models.Model):
    #PRODUCT_TYPE_CHOICES = [
    #    ('EPC', 'Electric pressure cooker'),
    #    ('IC', 'Induction cooker'),
    #    ('O', 'Other'),
    #]
    
    #PURCHASE_MODE_CHOICES = [
        #('C', 'Cash'),
        #('DA', 'Deposit Account'),
        #('P', 'PAYGO'),
    #]
    #TYPE_OF_USE_CHOICES = [
        #('Domestic', 'Domestic'),
        #('Business', 'Business'),
        #('Other', 'Other')
    #]
    #PAYMENT_PLAN_CHOICES = [
        #('Wholesale', 'Wholesale 10,600'),
        #('Plan_1', 'Plan 1: Deposit 4,500 with weekly payments of 190 for 40 weeks(12,100)'),
        #('Plan_2', 'Plan 2: Deposit 2,500 with weekly payments of 250 for 48 weeks(14,500)'),
        #('Retail', 'Retail 12,100')
    #]
    
    customer = models.ForeignKey(InternalCustomer, on_delete=models.CASCADE, related_name='sales')
    #registration_date = models.DateField()
    release_date = models.DateField(blank=True, null=True)
    #product_type = models.CharField(max_length=3, choices=PRODUCT_TYPE_CHOICES)
    product_name = models.CharField(max_length=255)
    product_model = models.CharField(max_length=255)
    product_serial_number = models.CharField(max_length=255)
    #purchase_mode = models.CharField(max_length=100)
    #referred_by = models.ForeignKey(InternalCustomer, on_delete=models.SET_NULL, blank=True, null=True,
                                    #related_name='referrals')
    sales_rep = models.CharField(max_length=255)
    date = models.DateTimeField(auto_now_add=True)
    #metered = models.BooleanField(default=False)
    #type_of_use = models.CharField(max_length=10, choices=TYPE_OF_USE_CHOICES, default='Domestic')
    #specific_economic_activity = models.CharField(max_length=255, null=True, blank=True)
    #location_of_use = models.CharField(max_length=255, null=True, blank=True)
    payment_plan = models.CharField(max_length=100) 
    dealer_name = models.CharField(max_length=255)

    #def save(self, *args, **kwargs):
        # Set default payment plan based on purchase mode
        #if not self.payment_plan:
            #if self.purchase_mode == 'C':  # Cash Purchase
                #self.payment_plan = 'Retail'
            #else:  # Other purchase modes
                #self.payment_plan = 'Plan_1'

        #super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.product_name} ({self.product_model})"

    class Meta:
        db_table = 'customer_sales_sale_internal'  # Default table for regular users

################################################END OF INTERNAL MODELS################################


###############################################SCODE MODELS###########################################
class Customer(models.Model):
    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female'),
        ('P', 'Prefer not to say'),
        ('O', 'Other'),
    ]
    
    HOUSEHOLD_CHOICES = [
        ('M', 'Male headed'),
        ('F', 'Female headed'),
        ('C', 'Child headed'),
        ('O', 'Other'),
        ('P', 'Prefer not to say'),
    ]
    
    LANGUAGE_CHOICES = [
        ('EN', 'English'),
        ('SW', 'Kiswahili'),
        ('NA', 'Native'),
    ]

    name = models.CharField(max_length=255)
    id_number = models.CharField(max_length=20, unique=True)
    phone_number = models.CharField(max_length=15)
    alternate_phone_number = models.CharField(max_length=15, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    country = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    household_type = models.CharField(max_length=1, choices=HOUSEHOLD_CHOICES)
    household_size = models.IntegerField()
    preferred_language = models.CharField(max_length=2, choices=LANGUAGE_CHOICES)
    date = models.DateTimeField(auto_now_add=True)
    county = models.CharField(max_length=100, null=True, blank=True)
    sub_county = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'customer_sales_customer'  # Default table for regular users


class Sale(models.Model):
    PRODUCT_TYPE_CHOICES = [
        ('EPC', 'Electric pressure cooker'),
        ('IC', 'Induction cooker'),
        ('O', 'Other'),
    ]
    
    PURCHASE_MODE_CHOICES = [
        ('C', 'Cash'),
        ('DA', 'Deposit Account'),
        ('P', 'PAYGO'),
    ]
    TYPE_OF_USE_CHOICES = [
        ('Domestic', 'Domestic'),
        ('Business', 'Business'),
        ('Other', 'Other')
    ]
    PAYMENT_PLAN_CHOICES = [
        ('Wholesale', 'Wholesale 10,600'),
        ('Plan_1', 'Plan 1: Deposit 4,500 with weekly payments of 190 for 40 weeks(12,100)'),
        ('Plan_2', 'Plan 2: Deposit 2,500 with weekly payments of 250 for 48 weeks(14,500)'),
        ('Retail', 'Retail 12,100')
    ]
    
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='sales')
    registration_date = models.DateField()
    release_date = models.DateField(blank=True, null=True)
    product_type = models.CharField(max_length=3, choices=PRODUCT_TYPE_CHOICES)
    product_name = models.CharField(max_length=255)
    product_model = models.CharField(max_length=255)
    product_serial_number = models.CharField(max_length=255)

customer_sales/templates/customer_sales/add_item.html
{% extends 'layout.html'%}

{% block title %} Powerpay Africa: Add New Item{% endblock %}

{% block content %}
<div class="container">
        <h2>Add New Item</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Add Item</button>
        </form>
</div>
{% endblock %}

customer_sales/templates/customer_sales/add_warehouse.html
{% extends 'layout.html'%}

{% block title %} Powerpay Africa: Add New Warehouse{% endblock %}

{% block content %}
<div class="container">
        <h2>Add New Warehouse</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Add Warehouse</button>
        </form>
</div>
{% endblock %}

customer_sales/templates/customer_sales/bulk_move.html
{% extends "layout.html" %}

{% block title %} Powerpay Africa: Move Bulk Items {% endblock %}

{% block content %}

<h2>Bulk Move Items</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Move Items</button>
</form>

{% endblock %}

customer_sales/templates/customer_sales/customers_list.html
{% extends 'layout.html' %}

{% block title %}Powerpay Africa: Customers{% endblock %}

{% block content %}
<div class="container">
    <h2><i class="fa fa-users" aria-hidden="true" style='color:#0ead00'></i> Customers</h2>
    <div class="search-container">
        <form method="get" action="{% url 'customers_list' %}">
            <input type="text" name="q" value="{{ query }}" placeholder="Search Customer by name">
            <button type="submit">Search</button>
            <a href="{% url 'customers_list' %}" class="clear-search">Clear</a>
        </form>
    </div>
    {% if user.first_name != 'Sayona-Guest' %}
    <div style="margin-bottom:20px; float:left">
    <form method="get" action="{% url 'add_customer' %}">
        <!-- <input type="hidden" name="all_devices" value="{{ device_list|join:',' }}"> -->
        <button type="submit" class="device_data_btn">Add New Customer</button>
    </form>
    </div>
    {% endif %}
    <div style="margin-bottom:10px; float:right;">
        <a href="{% url 'export_customers' %}" class="add-device-btn">Export Customer Data</a>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th class="table_headers">Name</th>
                <th class="table_headers">National ID</th>
                <th class="table_headers">Phone Number</th>
                <th class="table_headers">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for customer in customers %}
            <tr>
                <td class="table_content">{{ customer.name }}</td>
                <td class="table_content">{{ customer.id_number }}</td>
                <td class="table_content">{{ customer.phone_number }}</td>
                <td class="table_content">
                    <a href="{% url 'customer_detail' customer.pk %}">🕵️‍♀️ Details</a> {% if user.first_name != 'Sayona-Guest' %}|
                    <a href="{% url 'customer_edit' customer.pk %}">📝 Edit</a> |
                    <a href="{% url 'customer_delete' customer.pk %}">❌ Delete</a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="pagination">
        <span class="step-links">
            {% if customers.has_previous %}
                <a href="?page=1{% if query %}&q={{ query }}{% endif %}">&laquo; first</a>
                <a href="?page={{ customers.previous_page_number }}{% if query %}&q={{ query }}{% endif %}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ customers.number }} of {{ customers.paginator.num_pages }}.
            </span>

            {% if customers.has_next %}
                <a href="?page={{ customers.next_page_number }}{% if query %}&q={{ query }}{% endif %}">next</a>
                <a href="?page={{ customers.paginator.num_pages }}{% if query %}&q={{ query }}{% endif %}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>
<style>
    .add-device-btn {
        text-decoration: none;
        padding: 10px;
        border-radius: 10px;
        background-color: #0ead00;
        color: #fff;
        text-align: center;
    }
    .add-device-btn:hover {
        background-color: #e68a00; 
    }
</style>
{% endblock %}

customer_sales/templates/customer_sales/item_delete.html
{% extends 'layout.html' %}

{% block title %}Powerpay Africa: Delete Item{% endblock %}

{% block content %}
<div class="container">
    <h2>Delete Item</h2>
    <p>Are you sure you want to delete item {{ item.name }} ?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Delete</button>
        <a href="{% url 'customers_list' %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock %}

customer_sales/templates/customer_sales/item_edit.html
{% extends 'layout.html' %}

{% block title %}Powerpay Africa: Edit Item{% endblock %}

{% block content %}
<div class="container">
    <h2>Edit Item</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>
{% endblock %}

customer_sales/templates/customer_sales/item_list.html
{% extends "layout.html" %}
{% load humanize %}
{% block title %} Powerpay Africa: Items {% endblock %}

{% block content %}

<div class='container'>
    <h2><i class="fa fa-tags" aria-hidden="true" style='color:#0ead00'></i> Items</h2>
    <div class="data-labels">
        <label class="labelArea"><i class="fa fa-tags" aria-hidden="true"></i>&emsp;Total Items:<br>{{ item_count|intcomma }} </label>
        <label class="labelArea"><i class="fa fa-tag" aria-hidden="true"></i>&emsp;Total Distinct Items:<br>{{ distinct_item_count|intcomma }} </label>
</div>
    <div class="search-container">
        <form method="get" action="{% url 'item_list' %}">
            <input type="text" name="q" value="{{ query }}" placeholder="Search by name">
            <button type="submit">Search</button>
            <a href="{% url 'item_list' %}" class="clear-search">Clear</a>
        </form>
    </div>
    <div style="margin-bottom:20px; float:left">
    <form method="get" action="{% url 'item_add' %}">
        <button type="submit" class="device_data_btn">Add New Item</button>
    </form>
    </div>
     <div style="margin-bottom:20px; float:right">
    <form method="get" action="{% url 'bulk_move_items' %}">
        <button type="submit" class="device_data_btn">Move Bulk Items</button>
    </form>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th class="table_headers">Name</th>
                <th class="table_headers">Product Type</th>
                <th class="table_headers">Product Serial Number</th>
                <th class="table_headers">Date Added</th>
                <th class="table_headers">Warehouse</th>
                <th class="table_headers">Days in Warehouse</th>
                <th class="table_headers">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for item in items %}
            <tr>
                <td class="table_content">{{ item.name }}</td>
                <td class="table_content">{{ item.product_type }}</td>
                <td class="table_content">{{ item.serial_number }}</td>
                <td class="table_content">{{ item.date_added|date:"d M Y" }}</td>
                <td class="table_content">{{ item.current_warehouse.name }}</td>
                <td class="table_content">{{ item.days_in_current_warehouse }} {% if item.days_in_current_warehouse == 1 %} day {% else %} days {% endif %}</td>
                <td class="table_content">
                    <a href="{% url 'item_detail' item.pk %}">🕵️‍♀️ Details</a> |
                    <a href="{% url 'item_edit' item.pk %}">📝 Edit</a> |
                    <a href="{% url 'item_delete' item.pk %}">❌ Delete</a> |
                    <a href="{% url 'move_inventory_item' item.pk %}">🔄️ Move Item</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="pagination">
        <span class="step-links">
            {% if items.has_previous %}
                <a href="?page=1{% if query %}&q={{ query }}{% endif %}">&laquo; first</a>
                <a href="?page={{ items.previous_page_number }}{% if query %}&q={{ query }}{% endif %}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ items.number }} of {{ items.paginator.num_pages }}.
            </span>

            {% if items.has_next %}
                <a href="?page={{ items.next_page_number }}{% if query %}&q={{ query }}{% endif %}">next</a>
                <a href="?page={{ items.paginator.num_pages }}{% if query %}&q={{ query }}{% endif %}">last &raquo;</a>
            {% endif %}
        </span>
    </div>

</div>

{% endblock %}

customer_sales/templates/customer_sales/move_item.html
{% extends "layout.html" %}

{% block title %}Powerpay Africa: Move Item{% endblock %}

{% block content %}
<h2>Move Item: {{ item.name }} ({{ item.serial_number }})</h2>

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Move Item</button>
</form>
{% endblock %}

customer_sales/templates/customer_sales/sale_confirm_delete.html
{% extends 'layout.html' %}

{% block title %}Delete Sale{% endblock %}

{% block content %}
<div class="container">
    <h2>Delete Sale</h2>
    <p>Are you sure you want to delete this sale?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="device_data_btn">Delete</button>
        <a href="{% if sale.customer %}{% url 'customer_detail' sale.customer.pk %}{% else %}{% url 'sales_list' %}{% endif %}" class="device_data_btn">Cancel</a>
    </form>
</div>
{% endblock %}

customer_sales/templates/customer_sales/sale_detail.html
{% extends 'layout.html' %}

{% block title %}Powerpay Africa: Sale Details{% endblock %}

{% block content %}
<div class="container">
    <h2>Sale Details</h2>
    <p><strong>Product Name:</strong> {{ sale.product_name }}</p>
    <p><strong>Product Model:</strong> {{ sale.product_model }}</p>
    <p><strong>Product Serial Number:</strong> {{ sale.product_serial_number }} {% if sale.metered %} <form method="get" action="{% url 'device_data_page' deviceID=sale.product_serial_number %}">
        <button type="submit" class="device_data_btn"> {{ sale.product_serial_number }} data</button>
    </form> {% endif %}</p>
    <p><strong>Registration Date:</strong> {{ sale.registration_date|date:"d M Y " }}</p>
    <p><strong>Release Date:</strong> {{ sale.release_date|date:"d M Y " }}</p>
    <p><strong>Product Type:</strong> {{ sale.get_product_type_display }}</p>
    <p><strong>Purchase Mode:</strong> {{ sale.get_purchase_mode_display }}</p>
    <p><strong>Payment Plan:</strong> {{ sale.get_payment_plan_display }}</p>
    <p><strong>Customer:</strong> {{ sale.customer.name }} <form method="get" action="{% url 'customer_detail' pk=sale.customer.pk %}">
        <button type="submit" class="device_data_btn"> See Customer data</button>
    </form></p>
    <p><strong>Referred By:</strong> {{ sale.referred_by.name }}</p>
    <p><strong>Sales Rep:</strong> {{ sale.sales_rep }}</p>
    <p><strong>Metered:</strong> {% if sale.metered %}Yes{% else %}No{% endif %}</p>
    <p><strong>Type of Use:</strong> {{ sale.get_type_of_use_display }}</p>
    <p><strong>Specific Economic Activity:</strong> {{ sale.specific_economic_activity }}</p>
    <p><strong>Location of Use:</strong> {{ sale.location_of_use }}</p>
</div>
{% endblock %}

customer_sales/templates/customer_sales/sale_form.html
{% extends 'layout.html' %}

{% block title %}Powerpay Africa: {{ form.instance.pk|yesno:"Edit Sale,Add Sale" }}{% endblock %}

{% block content %}
<div class="container">
    <h2>{{ form.instance.pk|yesno:"Edit Sale,Add Sale" }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="device_data_btn">{{ form.instance.pk|yesno:"Update,Save" }}</button>
    </form>
</div>
{% endblock %}

customer_sales/templates/customer_sales/warehouse_list.html
{% extends "layout.html" %}

{% block title %} Powerpay Africa: Warehouses {% endblock %}

{% block content %}

<div class='container'>
    <h2><i class="fa fa-building" aria-hidden="true" style='color:#0ead00'></i> Warehouses</h2>
    <div class="search-container">
        <form method="get" action="{% url 'warehouse_list' %}">
            <input type="text" name="q" value="{{ query }}" placeholder="Search by name">
            <button type="submit">Search</button>
            <a href="{% url 'warehouse_list' %}" class="clear-search">Clear</a>
        </form>
    </div>
    <div style="margin-bottom:20px">
    <form method="get" action="{% url 'warehouse_add' %}">
        <button type="submit" class="device_data_btn">Add New Warehouse</button>
    </form>
    </div>
     <div style="float:right; margin-bottom:20px;">
        <a href="{% url 'export_items' %}" class="add-device-btn">Export Inventory List</a>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th class="table_headers">Name</th>
                <th class="table_headers">Location</th>
                <th class="table_headers">Item Count</th>
                <th class="table_headers">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for warehouse in warehouses %}
            <tr>
                <td class="table_content">{{ warehouse.name }}</td>
                <td class="table_content">{{ warehouse.location }}</td>
                <td class="table_content">{{ warehouse.item_count }}</td>
                <td class="table_content">
                    <a href="{% url 'warehouse_detail' warehouse.pk %}">🕵️‍♀️ Details</a> |
                    <a href="{% url 'warehouse_edit' warehouse.pk %}">📝 Edit</a> |
                    <a href="{% url 'warehouse_delete' warehouse.pk %}">❌ Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="pagination">
        <span class="step-links">
            {% if warehouses.has_previous %}
                <a href="?page=1{% if query %}&q={{ query }}{% endif %}">&laquo; first</a>
                <a href="?page={{ warehouses.previous_page_number }}{% if query %}&q={{ query }}{% endif %}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ warehouses.number }} of {{ warehouses.paginator.num_pages }}.
            </span>

            {% if warehouses.has_next %}
                <a href="?page={{ warehouses.next_page_number }}{% if query %}&q={{ query }}{% endif %}">next</a>
                <a href="?page={{ warehouses.paginator.num_pages }}{% if query %}&q={{ query }}{% endif %}">last &raquo;</a>
            {% endif %}
        </span>
    </div>

</div>
<style>
    .add-device-btn {
        text-decoration: none;
        padding: 10px;
        border-radius: 10px;
        background-color: #0ead00;
        color: #fff;
        text-align: center;
    }
    .add-device-btn:hover {
        background-color: #e68a00; 
    }
</style>
{% endblock %}